POS/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using POS.Models;
using POS.Services;

namespace POS.Controllers;

public class ProductController : Controller
{
    private readonly ProductService _service;
    
    public ProductController(ProductService productService)
    {
        _service = productService;
    }
    
    // GET
    public IActionResult Index()
    {
        var products = _service.GetProductsEnabled();
        return View(products);
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    public IActionResult Edit(string id)
    {
        var product = _service.GetProductById(id);
        return View(product);
    }
    
    // HTTP METHODS
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductModel product)
    {
        if (ModelState.IsValid)
        {
            product.Status = true;
            Console.Write(product.ToJson());
            _service.CreateProduct(product);
            return RedirectToAction(nameof(Index));
        }
        return View(product);
    }
    
    [HttpGet("/Product/GetProductsEnabled")]
    public IActionResult GetAll()
    {
        var products = _service.GetProductsEnabled();
        return Json(products);
    }
    
    [HttpGet("Product/GetByCode/{code}")]
    public IActionResult GetByCode(string code)
    {
        var product = _service.GetProductByCode(code);
        return Json(product);
    }
    
    [HttpGet("Product/Search/{term}")]
    public IActionResult Search(string term)
    {
        var product = _service.SearchProducts(term);
        return Json(product);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(string id, ProductModel product)
    {
        if (ModelState.IsValid)
        {
            product.Status = true;
            Console.Write(product.ToJson());
            _service.UpdateProduct(id, product);
            return RedirectToAction(nameof(Index));
        }
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(string id)
    {
        _service.DisableProduct(id);
        return RedirectToAction(nameof(Index));
    }
}

POS/Controllers/SaleController.cs
using System.Diagnostics;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using POS.Models;
using POS.Services;

namespace POS.Controllers;

public class SaleController : Controller
{
    private readonly ILogger<SaleController> _logger;
    private readonly SaleService _saleService;
    private readonly SupervisorService _supervisorService;
    private readonly ProductService _productService;
    private readonly CanceledSaleService _canceledSaleService;

    public SaleController
    (
        ILogger<SaleController> logger,
        SaleService saleService, 
        SupervisorService supervisorService,
        ProductService productService,
        CanceledSaleService canceledSaleService
        )
    {
        _logger = logger;
        _saleService = saleService;
        _supervisorService = supervisorService;
        _productService = productService;
        _canceledSaleService = canceledSaleService;
    }
    
    // GET
    public IActionResult Index()
    {
        var sales = _saleService.GetAllSales();
        return View(sales);
    }
    
    public IActionResult CanceledIndex()
    {
        var canceledSales = _canceledSaleService.GetAll();
        var sales = _saleService.GetCanceledSales();
    
        var viewModelList = new List<CanceledSaleViewModel>();
        foreach(var canceledSale in canceledSales)
        {
            var sale = sales.FirstOrDefault(s => s.Id == canceledSale.SaleId.ToString());

            if(sale != null)
            {
                viewModelList.Add(new CanceledSaleViewModel 
                {
                    Sale = sale,
                    CanceledSale = canceledSale
                });
            }
            else
            {
                Console.WriteLine("Sale not found");
            }
        }

        return View(viewModelList);
    }

    public IActionResult Details(string id)
    {
        SaleModel sale = _saleService.GetSale(id);

        var productCodes = sale.SaleDetails.Select(s => s.Code).Distinct().ToList();
        var relatedProducts = _productService.GetProductsByCodes(productCodes);
        var productMap = relatedProducts.ToDictionary(p => p.Code, p => p);
        ViewBag.ProductMap = productMap;

        return View(sale);
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost("/Sale/Register")]
    public async Task<IActionResult> Register()
    {
        try
        {
            using var reader = new StreamReader(Request.Body);
            var body = await reader.ReadToEndAsync();

            if (string.IsNullOrEmpty(body))
            {
                return BadRequest("Body is null or empty");
            }

            var sale = JsonSerializer.Deserialize<SaleModel>(body);

            if (!ModelState.IsValid) return BadRequest();
            _saleService.CreateSale(sale);
            _productService.SubstractStock(sale.SaleDetails);
            return Ok();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
            return BadRequest(ex.Message);
        }
    }
    
    [HttpPost]
    public IActionResult CancelSale(SaleModel sale)
    {
        if(sale.Id == null || sale.Id.Equals("")) 
        {
            return BadRequest("Id de venta inválido");
        }

        _saleService.CancelSale(sale.Id);
        
        var saleOrigin = _saleService.GetSale(sale.Id);
        
        // add stock back to products
        foreach(var saleDetail in saleOrigin.SaleDetails)
        {
            var productCode = saleDetail.Code;
            var product = _productService.GetProductByCode(productCode);
            product.Stock += saleDetail.Quantity;
            _productService.UpdateProduct(product.Id.ToString(), product);
        }
        
        return RedirectToAction("Index");
    }

    [HttpPost("/VerifySupervisorToken")]
    public IActionResult VerifySupervisorToken(string token)
    {
        Console.WriteLine($"Token: {token}");
        var supervisor = _supervisorService.GetSupervisorByToken(token);
        if (supervisor == null)
        {
            return BadRequest(new { isValid = false, message = "Token del supervisor inválido." });
        }
    
        return Ok(new { isValid = true });
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

POS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - POS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/POS.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Sale" asp-action="Create">Nueva Venta</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Todas la Ventas
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Sale" asp-action="Index">Historial de Ventas</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Sale" asp-action="CanceledIndex">Ventas Canceladas</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Productos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Todos los Productos</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Create">Regitrar Producto</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - POS - <a asp-area="" asp-controller="" asp-action="">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>